### ISSUE TITLE
HomeKit automation to turn off aircon sometimes turns on aircon when it’s already off

### ISSUE THREAD

**Issue by TommyGKiwi** [takeya0x86/homebridge-nature-remo-platform#64]
**Describe The Bug:**
Have an automation in homekit to turn off aircon when the window is open
Sometimes when the window opens the AirCon turns on/or stays on(there was a beep)

**To Reproduce:**
Intermittent but quite often, open window that triggers turn off aircon command

**Expected behavior:**
Should just turn off the AirCon.  Aircon off command is off only command (at least using remote button)

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**
 "name": "Nature Remo Platform",            "accessToken": "Xxxxxxxx",            "LIGHT": false,            "AC": true,            "TV": false,            "platform": "NatureRemoPlatformPlugin"

**Screenshots:**
/
![IMG_0953](https://user-images.githubusercontent.com/46218042/179633267-fb30d0c9-c47d-41ac-93d3-3af997ba46b4.jpg)

**Environment:**

* **Plugin Version**: 2.0.1
* **Homebridge Version**:  1.5.0
* **Node.js Version**:  16.16.0
* **NPM Version**: 
* **Operating System**:  Raspbian

**Comment by TommyGKiwi** [comment]
I think when a HomeKit command arrives near the same time as nature remo status arrives that nature remo status over writes the comnand and sends the nature status I the command instead of the HomeKit request

**Comment by takeyaqa** [comment]
Sorry, I can't reproduce it.
